name: purchaseorders2
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  dropdown_button2: ^2.3.9
  intl: ^0.20.2
  provider: ^6.1.5
  pdf: ^3.11.3
  printing: ^5.14.2
  path_provider: ^2.1.5
  dio: ^5.8.0+1
  google_fonts: ^6.2.1
  connectivity_plus: ^6.0.3
  share_plus: ^7.2.1
  file_picker: ^8.0.0
  open_filex: ^4.3.2
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.1.0
  image_picker: 1.0.7
  mocktail: ^1.0.0

  uuid: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/bestmummy.jpg
    - assets/fonts/NotoSans-VariableFont_wdth,wght.ttf